// Snazzle v100 — stabiele start, premium Home en één vast menu.
const rv=new URL(import.meta.url).searchParams.get('v')||Date.now().toString();
const fresh=p=>`${p}${p.includes('?')?'&':'?'}fresh=${encodeURIComponent(rv)}`;
window.__snazzleRuntimeVersion=rv;window.__snazzleFresh=fresh;window.__snazzleCoreReady=false;
const loaded=new Map(),sleep=ms=>new Promise(r=>setTimeout(r,ms));let corePromise,busy=false;
const settings=()=>{try{return JSON.parse(localStorage.getItem('snazzleSettings')||'{}')}catch{return{}}};
const village=()=>localStorage.getItem('snazzleVillage')||'Montfort';
for(const p of ['./snazzle-magic-theme.css','./snazzle-enchanted-layer.css','./snazzle-professional-v53.css','./snazzle-final-polish-v59.css']){const l=document.createElement('link');l.rel='stylesheet';l.href=fresh(p);document.head.appendChild(l)}

let released=false;
function boot(){if(!document.body||document.getElementById('snV100Boot'))return;const s=settings(),img=s.introImage||s.profileImage||'';const mark=img?`<img src="${img}" alt="Snazzle" style="width:100%;height:100%;object-fit:cover;display:block">`:`<svg viewBox="0 0 120 120" style="width:90px;height:90px"><ellipse cx="50" cy="72" rx="34" ry="24" fill="#34afe8"/><circle cx="78" cy="44" r="22" fill="#34afe8"/><path d="M96 42 118 50 96 58Z" fill="#f6a323"/><circle cx="83" cy="39" r="4" fill="#14251b"/><path d="M24 68 8 56 12 80Z" fill="#34afe8"/></svg>`;const d=document.createElement('div');d.id='snV100Boot';d.style.cssText='position:fixed;inset:0;z-index:99999;display:grid;place-items:center;background:linear-gradient(180deg,#17684c,#083a31);color:#fff7df;text-align:center;font-family:system-ui;transition:opacity .2s';d.innerHTML=`<div style="font-weight:900"><div style="width:116px;height:116px;margin:auto;border-radius:50%;overflow:hidden;display:grid;place-items:center;background:#ffd45a;border:5px solid #76502d;box-shadow:0 8px 0 #4a2b18">${mark}</div><div style="font-size:44px;color:#ffd35e;margin-top:22px">Snazzle</div><div style="font-size:20px;margin-top:10px">Samen naar buiten</div><div style="font-size:14px;margin-top:20px">Je avontuur wordt klaargezet…</div></div>`;document.body.appendChild(d)}
function release(){if(released)return;released=true;const d=document.getElementById('snV100Boot')||document.getElementById('snV98Boot')||document.getElementById('snV59Boot');if(d){d.style.opacity='0';d.style.pointerEvents='none';setTimeout(()=>d.remove(),230)}}
if(document.body)boot();else document.addEventListener('DOMContentLoaded',boot,{once:true});setTimeout(release,3000);

function toast(t){const e=document.getElementById('toast');if(!e)return;e.textContent=t;e.classList.add('show');clearTimeout(window.__v100toast);window.__v100toast=setTimeout(()=>e.classList.remove('show'),2000)}
async function load(p,ms=6000){if(loaded.has(p))return loaded.get(p);let timer;const x=Promise.race([import(fresh(p)),new Promise((_,rej)=>timer=setTimeout(()=>rej(new Error('timeout')),ms))]).finally(()=>clearTimeout(timer)).catch(e=>{loaded.delete(p);throw e});loaded.set(p,x);return x}

const items=[['🏠','Home','Terug naar het begin','home'],['🔎','Hunt zoeken','Bekijk de actieve Hunt','hunt'],['📍','Kies je dorp','Montfort en andere dorpen','village'],['🎮','Snazzle Spel','Jouw Snazzle Wereld','game'],['🎧','Luisterverhalen','Luister naar verhalen','listen'],['📚','De Bieb','Lezen en je leeshoek','bieb'],['✨','Mijn Collectie','Kaarten, Nest & jaarstand','collection'],['📷','Snazzle AR','Zoek met camera en GPS','ar'],['🗞️','Snazzle Nieuws','Nieuws en verhalen','news'],['👥','Vrienden','Bekijk actieve Snazzlers','friends'],['🏆','Mijn vondsten','Jouw gevonden hunts','findings'],['🎉','Actie & evenement','Open de actuele poster','event'],['🛍️','Shop','Bekijk Snazzle items','shop'],['👤','Mijn profiel','Naam aanpassen','profile'],['👨‍👩‍👧','Voor ouders','Veiligheid en privacy','parents']];
function menuCss(){if(document.getElementById('menuV100css'))return;const s=document.createElement('style');s.id='menuV100css';s.textContent=`#quickMenuBtn.v100{width:58px;height:58px;border-radius:19px;border:3px solid #8b6538;background:linear-gradient(145deg,#397844,#1f5735);color:#fff;font-size:31px;font-weight:1000;box-shadow:0 6px 0 #4c2f1d;padding:0}#quickMenuOverlay.v100{position:fixed;inset:0;z-index:12000;background:#020e08c7;display:none;justify-content:flex-end}#quickMenuOverlay.v100.show{display:flex!important}#quickMenuPanel.v100{width:min(91vw,405px);height:100%;overflow:auto;padding:calc(17px + env(safe-area-inset-top)) 14px calc(26px + env(safe-area-inset-bottom));background:linear-gradient(#17633a,#07331f);border-left:4px solid #9a7040;color:#fff8df;box-sizing:border-box}.mhead{display:flex;align-items:center;justify-content:space-between;border-bottom:2px solid #ffda7038;padding-bottom:14px}.mbrand{display:flex;align-items:center;gap:10px}.mduck{width:50px;height:50px;border-radius:50%;display:grid;place-items:center;background:#ffd45b;border:3px solid #754720;font-size:26px}.mbrand strong{display:block;color:#ffd34b;font-size:21px}.mbrand small{color:#c9ef8a;font-weight:800}.mclose{width:44px;height:44px;border:0;border-radius:14px;background:#724328;color:#fff;font-size:27px}.mlabel{margin:13px 3px 9px;color:#c9ef8a;font-size:11px;font-weight:1000;text-transform:uppercase}.mlist{display:grid;gap:7px}.mi{width:100%;min-height:61px;border:2px solid #ffe29a35;border-radius:16px;background:#ffffff16;color:#fff8df;padding:8px 10px;display:grid;grid-template-columns:42px 1fr 20px;align-items:center;gap:8px;text-align:left}.mi b{font-size:23px}.mi strong{display:block;font-size:15px}.mi small{display:block;margin-top:3px;color:#d7e9bd;font-size:10px}.mi i{font-style:normal;font-size:28px;color:#ffd34b}.madmin{margin-top:11px;background:#593820}.mfoot{text-align:center;color:#a9dc72;font-size:11px;font-weight:900;margin:16px 0}`;document.head.appendChild(s)}
function buildMenu(){menuCss();const old=document.getElementById('quickMenuPanel');if(old?.dataset.owner==='v100')return;document.getElementById('quickMenuOverlay')?.remove();document.getElementById('quickMenuBtn')?.remove();const top=document.querySelector('.top');if(!top)return;const admin=document.getElementById('adminBtn');if(admin)admin.style.display='none';const b=document.createElement('button');b.id='quickMenuBtn';b.className='v100';b.textContent='☰';b.type='button';top.appendChild(b);const o=document.createElement('div');o.id='quickMenuOverlay';o.className='v100';o.innerHTML=`<aside id="quickMenuPanel" class="v100" data-owner="v100"><div class="mhead"><div class="mbrand"><span class="mduck">🦆</span><div><strong>Snazzle Menu</strong><small id="quickMenuVillage">📍 ${village()}</small></div></div><button id="quickMenuClose" class="mclose">×</button></div><div class="mlabel">Alles van Snazzle</div><nav class="mlist">${items.map(([i,t,s,k])=>`<button class="mi" data-a="${k}"><b>${i}</b><span><strong>${t}</strong><small>${s}</small></span><i>›</i></button>`).join('')}</nav><button class="mi madmin" data-a="admin"><b>🔒</b><span><strong>Beheer</strong><small>Voor beheerders</small></span><i>›</i></button><div class="mfoot">Samen naar buiten 🌿</div></aside>`;document.body.appendChild(o);const close=()=>{o.classList.remove('show');document.body.style.overflow='';document.documentElement.style.overflow=''};b.onclick=()=>{const v=document.getElementById('quickMenuVillage');if(v)v.textContent='📍 '+village();o.classList.add('show');document.body.style.overflow='hidden';document.documentElement.style.overflow='hidden'};document.getElementById('quickMenuClose').onclick=close;o.onclick=e=>{if(e.target===o)close()};o.querySelectorAll('[data-a]').forEach(x=>x.onclick=async()=>{const a=x.dataset.a;close();await action(a)})}
if(document.body)buildMenu();else document.addEventListener('DOMContentLoaded',buildMenu,{once:true});

async function feature(label,fn){if(busy)return;busy=true;try{toast(label);await corePromise;await fn()}catch(e){console.warn(e);toast('Dit onderdeel kon nu niet openen.')}finally{busy=false;buildMenu()}}
async function action(a){if(a==='home'){scrollTo(0,0);return}if(a==='village'){document.querySelector('.villages')?.scrollIntoView({behavior:'smooth',block:'center'});return}const click={hunt:'#navHunt',friends:'#navFriends',findings:'#findsBtn',shop:'#navShop',profile:'#navProfile',admin:'#adminBtn'}[a];if(click){await feature('Openen…',async()=>document.querySelector(click)?.click());return}if(a==='event'){await feature('Actie openen…',async()=>document.querySelector('.home-card:nth-child(2)')?.click());return}if(a==='game'){await feature('Snazzle Spel openen…',async()=>{await load('./snazzle-world-adventure-v38.js');await load('./snazzle-world-hub-v47.js');await load('./snazzle-game-menu-v62.js');window.SnazzleGameMenuV62?.open?.()});return}if(a==='listen'){await feature('Luisterverhalen openen…',async()=>{await load('./snazzle-listen-stories-v63.js');window.SnazzleListenStoriesV63?.open?.()});return}if(a==='bieb'){await feature('De Bieb openen…',async()=>{await load('./snazzle-bieb-v73.js');await load('./snazzle-bieb-cloud-v74.js');await load('./snazzle-bieb-locations-v77.js');window.SnazzleBiebV73?.open?.()});return}if(a==='collection'){await feature('Collectie openen…',async()=>{await load('./snazzle-collection.js');await load('./snazzle-card-system-v2.js');await load('./snazzle-card-worlds-v78.js');(document.querySelector('[data-snazzle-collection]')||document.getElementById('collectionHomeCard'))?.click()});return}if(a==='ar'){await feature('Snazzle AR openen…',async()=>{await load('./snazzle-ar-v80.js');await load('./snazzle-ar-safety-v82.js');document.getElementById('snArLaunch')?.click()});return}if(a==='news'){await feature('Snazzle Nieuws openen…',async()=>{await load('./snazzle-news-v46.js');document.getElementById('snNewsLaunch')?.click()});return}if(a==='parents'){await feature('Voor ouders openen…',async()=>{await load('./snazzle-parent-hub-v65.js');await load('./snazzle-parent-close-fix-v76.js');window.SnazzleParentHubV65?.open?.()})}}
window.SnazzleAppV100={action};

corePromise=import(fresh('./app-core.js')).then(async m=>{window.__snazzleCoreReady=true;buildMenu();try{await load('./snazzle-ui-v100.js',2500)}catch(e){console.warn(e)}window.SnazzleHomeV100?.restore?.();release();return m}).catch(e=>{console.error(e);release();toast('Verbinding is traag. Open opnieuw.');return null});
Promise.race([corePromise,sleep(2600)]).then(release);
corePromise.then(async c=>{if(!c)return;await sleep(500);for(const p of ['./snazzle-runtime-stability-v71.js','./snazzle-image-stability-v72.js','./snazzle-top-stability-v70.js'])try{await load(p,4000)}catch{}buildMenu();window.SnazzleHomeV100?.restore?.()});
corePromise.then(async c=>{if(!c)return;try{const {getAuth,onAuthStateChanged}=await import('https://www.gstatic.com/firebasejs/12.17.1/firebase-auth.js');let done=false;onAuthStateChanged(getAuth(),async u=>{if(!u||done)return;done=true;try{await load('./shop.js')}catch{}try{await load('./shop-email-settings.js')}catch{}})}catch{}});
