// Snazzle Home v100 — premium paspoort, avontuur en vaste tegels. Raakt het menu niet aan.
const $=(s,r=document)=>r?.querySelector?.(s)||null,$$=(s,r=document)=>r?.querySelectorAll?[...r.querySelectorAll(s)]:[];
const name=()=>localStorage.getItem('snazzleName')?.trim()||'',village=()=>localStorage.getItem('snazzleVillage')||'Montfort';

function css(){if($('#homeV100css'))return;const s=document.createElement('style');s.id='homeV100css';s.textContent=`
#snazzlePassportV100{margin:10px 0 16px;padding:20px 20px 17px;border-radius:27px;background:linear-gradient(145deg,#f6ebc7,#ead29a);color:#173d35;border:4px solid #b88f50;box-shadow:0 7px 0 #6a482a,0 14px 28px #0003;overflow:hidden}#snazzlePassportV100 .kick{font-size:10px;letter-spacing:1.7px;text-transform:uppercase;font-weight:1000;color:#8b6835;margin-bottom:9px}#snazzlePassportV100 #welcomeText{margin:0 0 16px!important;color:#17493f!important;text-shadow:none!important;font-size:35px!important;line-height:1.04!important;text-transform:none!important;font-weight:900!important}.pstats{display:grid;grid-template-columns:.85fr 1.1fr 1.15fr;border-top:1px dashed #5442254d;padding-top:12px}.pstat{padding:0 10px;border-right:1px solid #54422533;min-width:0}.pstat:first-child{padding-left:0}.pstat:last-child{border:0;padding-right:0}.pstat strong{display:block;font-size:16px;color:#123f35;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.pstat small{display:block;margin-top:2px;font-size:10px;color:#765d38;line-height:1.2}
#hero.homeV100{min-height:360px!important;padding:26px 22px!important;justify-content:flex-end!important;border-color:#77502d!important;box-shadow:0 8px 0 #442918,0 14px 30px #0004!important}#hero.homeV100 small{font-size:12px!important;letter-spacing:1.8px!important;color:#ffe899!important;margin-bottom:4px!important}#hero.homeV100 p{font-size:20px!important;font-weight:850!important;line-height:1.35!important;margin:0 0 20px!important;color:#fff!important;text-shadow:0 2px 5px #0008!important}#adventureV100{font-size:32px!important;line-height:1.05!important;margin:0!important;color:#fff!important;text-shadow:0 3px 9px #0009!important}
#homeFeaturesV100{display:grid!important;grid-template-columns:repeat(2,minmax(0,1fr))!important;gap:11px!important;margin:18px 0 5px!important;width:100%!important}.hf100{min-height:126px!important;border:4px solid #704824!important;border-radius:22px!important;padding:15px!important;color:#fff!important;text-align:left!important;display:flex!important;flex-direction:column!important;align-items:flex-start!important;justify-content:flex-end!important;box-shadow:0 6px 0 #432918,0 12px 22px #0003!important;appearance:none!important}.hf100:nth-child(1){background:linear-gradient(145deg,#4f7351,#24533a)!important}.hf100:nth-child(2){background:linear-gradient(145deg,#6557b9,#394c95)!important}.hf100:nth-child(3){background:linear-gradient(145deg,#8a6940,#59623c)!important}.hf100:nth-child(4){background:linear-gradient(145deg,#7259a7,#3f7285)!important}.hf100:nth-child(5){background:linear-gradient(145deg,#744cb4,#3d296f)!important}.hf100:nth-child(6){background:linear-gradient(145deg,#2f7550,#174b35)!important}.hf100 b{font-size:30px;line-height:1;margin-bottom:8px}.hf100 strong{display:block;font-size:17px;line-height:1.12}.hf100 small{display:block;margin-top:5px;color:#f3f2e0;font-size:11px;font-weight:700;line-height:1.3}@media(max-width:350px){#homeFeaturesV100{grid-template-columns:1fr!important}.hf100{min-height:96px!important}}
`;document.head.appendChild(s)}

function count(){const t=$('#passportFindsV100');if(!t)return;const rows=$$('#findsList .listitem').filter(x=>!x.textContent.includes('Nog niets gevonden'));t.textContent=String(rows.length)}
function go(a){if(window.SnazzleAppV100?.action){window.SnazzleAppV100.action(a);return}const m=$(`#quickMenuPanel [data-a="${a}"]`)||$(`#quickMenuPanel [data-sn-action="${a}"]`);if(m)m.click()}

function restore(){css();const top=$('.top'),welcome=$('#welcomeText');if(!top||!welcome)return;$('#snHomeFeaturesV99')?.remove();$('#snV96Features')?.remove();let p=$('#snazzlePassportV100');if(!p){p=document.createElement('section');p.id='snazzlePassportV100';p.innerHTML=`<div class="kick">Mijn Snazzle paspoort</div><div class="wslot"></div><div class="pstats"><div class="pstat"><strong id="passportFindsV100">0</strong><small>Snazzles gevonden</small></div><div class="pstat"><strong id="passportVillageV100"></strong><small>gekozen dorp</small></div><div class="pstat"><strong>Explorer</strong><small>klaar voor avontuur</small></div></div>`;top.insertAdjacentElement('afterend',p)}const slot=$('.wslot',p);if(slot&&welcome.parentElement!==slot)slot.appendChild(welcome);welcome.textContent=name()?`Hoi ${name()}!`:'Hoi!';const pv=$('#passportVillageV100');if(pv)pv.textContent=village();count();const hero=$('#hero');if(hero){hero.classList.add('homeV100');const k=hero.querySelector('small');if(k)k.textContent='Snazzle avontuur';const para=hero.querySelector('p');if(para)para.textContent='Vind een Snazzle en ontdek jouw dorp.';let h=$('#adventureV100',hero);if(!h){h=document.createElement('h2');h.id='adventureV100';hero.appendChild(h)}h.textContent='Klaar voor avontuur?'}const quick=$('.quick');if(quick&&!$('#homeFeaturesV100')){const sec=document.createElement('section');sec.id='homeFeaturesV100';for(const [i,t,s,a] of [['🎮','Snazzle Spel','Jouw Snazzle Wereld','game'],['✨','Mijn Collectie','Kaarten, Nest & jaarstand','collection'],['📚','De Bieb','Lezen en je leeshoek bouwen','bieb'],['🎧','Luisterverhalen','Luister naar Snazzle verhalen','listen'],['📷','Snazzle AR','Zoek met camera en GPS','ar'],['🗞️','Snazzle Nieuws','Nieuws en verhalen','news']]){const b=document.createElement('button');b.type='button';b.className='hf100';b.innerHTML=`<b>${i}</b><strong>${t}</strong><small>${s}</small>`;b.onclick=()=>go(a);sec.appendChild(b)}quick.insertAdjacentElement('afterend',sec)}document.documentElement.dataset.snazzleHome='v100'}

let timer;const schedule=()=>{clearTimeout(timer);timer=setTimeout(restore,60)};function init(){if(window.__homeV100)return;window.__homeV100=true;restore();const app=$('.app');if(app)new MutationObserver(schedule).observe(app,{childList:true,subtree:true,characterData:true});document.addEventListener('visibilitychange',()=>{if(document.visibilityState==='visible')schedule()})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();window.SnazzleHomeV100={restore};export{restore};
